### PR TITLE
prevent sending FAIL to cpantesters in case Test::More is too recent

### PR DESCRIPTION
**Pull request by chorny**

### CODE REVIEW

**Comment by rwstauner** [comment]
Thanks!
Do you know what would happen if we made this `exit 1` instead?  Seems more appropriate.

**Comment by rwstauner** [comment]
[cpan grep](http://grep.cpan.me/?q=file%3A%5E%28Makefile%7CBuild%29%5C.PL%24+exit) shows mostly uses of `exit()` or `exit 0` but there are some instances of `exit 1`.

**Comment by chorny** [comment]
It would send UNKNOWN.

**Comment by rwstauner** [comment]
released.  thanks!

**Pull request merged**
